# Permalinks
permalink:           pretty

# Setup
title:               Abdullah Hanif
tagline:             A Moderately Okay Data Science Blog
url:                 http://ahanif19.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Abdullah Hanif
  url:               https://twitter.com/AbduIIahHanif
  email:             ahanif7926@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ahanif19

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
